### ISSUE TITLE
Drop support for Froyo?

### ISSUE THREAD

**Issue by vreixo** [CUTR-at-USF/OpenTripPlanner-for-Android#256]
I was working with gradle files, checking Espresso and Robolectric, for better testing support. Doing this, I have noticed that we are not using latest PlayServices 4.+, but the problem to use them is that they have dropped support for Froyo, because the number of users is very reduced now.

http://android-developers.blogspot.com.es/2013/10/google-play-services-40.html

**Comment by barbeau** [comment]
Froyo is down to 0.2% of Google Play users, and there are libraries I'd like to use (like [android-maps-util](https://github.com/googlemaps/android-maps-utils)) that require minSdkVersion of 9 or higher, or require newer version of Google Play Services.  So, time to drop Froyo support.

**Comment by barbeau** [comment]
Fixed via https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/commit/7d6799ff8ff1e5be07f25ef1ba9066237f6ce628.
