### ISSUE TITLE
Crash when planning a trip without selecting region

### ISSUE THREAD

**Issue by shyamsunder007** [CUTR-at-USF/OpenTripPlanner-for-Android#488]
In the beginning if i don't select any particular region, then if i select start and end location it crashes.

**Comment by barbeau** [comment]
Thanks for reporting @shyamsunder007!

**Comment by shyamsunder007** [comment]
@barbeau  Can i Send a PR on that

**Comment by barbeau** [comment]
@shyamsunder007 Yes, please!

**Comment by barbeau** [comment]
Without looking at the code a simple fix for this may be to disallow canceling the region selection dialog.
