### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [CUTR-at-USF/OpenTripPlanner-for-Android#490]
As there was no commit for almost 2 years: just wondering whether this project is still maintained. If not, you might consider "archiving" it (can be done in the project's settings, and can be undone there as well) to make it clear. Thanks!

**Comment by barbeau** [comment]
@IzzySoft It's still maintained, but not under active development.  There has been more recent work on OneBusAway Android related to multimodal trip planning.  But, this app remains an option for pure OTP deployments.  I'd prefer not to archive it so others can still comment on issues and pull requests.

**Comment by IzzySoft** [comment]
No reason to archive it if it's still maintained! So thanks for your reply. Good to know that eventual issues will still be dealt with – though new features are rather unlikely :wink:
