### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [CUTR-at-USF/OpenTripPlanner-for-Android#491]
With the last release more than 2 and the last commit almost 2 years ago, I wonder if this app is still maintained? Will there be future development and updates, @barbeau?

**Comment by barbeau** [comment]
@IzzySoft Asked and answered at https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/490.

**Comment by IzzySoft** [comment]
Uh… oh my. Apologies. Running through too many projects… Next time I'll find it, using this one as sign post…
